start: L1_A # possible values are listed in 'processors' fields (keys)
end: L2_SM # possible values are listed in 'processors' fields (keys); ending processor cannot be before the one in 'start' field  (following the order of the list 'processors')
logLevel: DEBUG
dataRoot: 'D:\HydroGNSS\E2ES\PDGS_NAS_folders'
backupRoot: 'D:\HydroGNSS\E2ES\RUNS'
processors: #available processors
  L1_A: 
    workingDirectory: 'D:\HydroGNSS\E2ES\L1APP' # absolute path to processor delivery
    executable: '' # relative path to processor executable
    args: # arguments list used for execution (order matters, must follow processor specific specs)
  L1_B:
    workingDirectory: 'D:\HydroGNSS\E2ES\L1BPP'
    executable: '.\bin\ZTCDataMerge.exe'
    args:
      - '"config=D:\HydroGNSS\L1BPP\processor\conf\hgdevConfiguration0p7_ReadL1a.xml,StartDateTime=20211210T03:00:00,StopDateTime=20211210T09:00:00"'
  L2_FB: 
    workingDirectory: 'D:\HydroGNSS\E2ES\L2PP-FB'
    executable: '.\L2PP_FB.exe'
    args:
      - '2021-12-10'
      - 'D:\HydroGNSS\L2PP\PDGS_NAS_folders'
  L2_SM:
    workingDirectory: 'D:\HydroGNSS\E2ES\L2PP-SSM'
    executable: '.\SML2PP_start.exe'
    args:
      - '-input'
      - 'D:\HydroGNSS\E2ES\PDGS_NAS_folders\DataRelease\L1A_L1B'
      - 'D:\HydroGNSS\E2ES\PDGS_NAS_folders\DataRelease\L2OP-SSM'
      - 'D:\HydroGNSS\E2ES\PDGS_NAS_folders\Auxiliary_Data'
      - '2021'
      - '12'
      - '12'
      - '1'
      - '25'
      - 'L1'
      - 'L'
  L2_FT:
    workingDirectory: 'D:\HydroGNSS\E2ES\L2PP-FT'
    executable: '.\L2PPFT.exe'
  L2_SI:
    workingDirectory: 'D:\HydroGNSS\E2ES\L2PP-SWS'
    executable: '.\L2_PSR.exe'
    args:
      - '-D'
      - 'D:\HydroGNSS\L2PP\PDGS_NAS_folders\DataRelease\L1A_L1B\2021-12\10\H06\DDMs.nc'
      - '-M'
      - 'D:\HydroGNSS\L2PP\PDGS_NAS_folders\DataRelease\L1A_L1B\2021-12\10\H06\metadata_L1_merged.nc'
      - '-R'
      - 'D:\HydroGNSS\L2PP\PDGS_NAS_folders\DataRelease\L2OP-SWS\out.nc'