start: L1_A
end: L1_A
PAM: True
logLevel: DEBUG
dataRoot: C:\PDGS_NAS_Folder
backupRoot: C:\E2ES_backups
backupFile:
processors:
  L1_A: 
    workingDirectory: C:\L1A\
    executable: .\bin\HSAVERS.exe
  L1_B:
    workingDirectory: C:\L1B\
    script: .\scripts\Run_L1b_Processor_with_dates.py
  L1_B2:
    workingDirectory: C:/L1OP-MM/scripts
    script: Run_L1Merge_with_dates.py
  L2_FB: 
    workingDirectory: C:\L2FB\
    executable: .\bin\L2PP_FB_v04.exe
  L2_SM:
    workingDirectory: C:\L2SM\
    executable: .\bin\SML2PP_start.exe
  L2_FT:
    workingDirectory: C:\L2FT\
    executable: .\bin\L2PPFT_mainscript.exe
  L2_SI:
    workingDirectory: C:\L2SI\
    script: .\scripts\Run_PSR.py
  PAM:
    workingDirectory: C:\PAM\
    executable: .\bin\PAM_start.exe
  
