start: L1_A
end: L1_A
logLevel: DEBUG
dataRoot: 'C:\Users\HydroGNSS\Desktop\PDGS_NAS_folder'
backupRoot: 'C:\Users\HydroGNSS\Desktop\DataRelease_backups'
backupFile:
dryMode: false
processors:
  L1_A: 
    workingDirectory: 'C:\Users\HydroGNSS\Desktop\L1APP\'
    executable: '.\bin\HSAVERS.exe'
  L1_B:
    workingDirectory: 'C:\Users\HydroGNSS\Desktop\L1BPP\'
    script: '.\scripts\Run_L1b_Processor_with_dates.py'
  L2_FB: 
    workingDirectory: 'C:\Users\HydroGNSS\Desktop\L2PPFB\'
    executable: '.\bin\L2PP_FB.exe'
  L2_SM:
    workingDirectory: 'C:\Users\HydroGNSS\Desktop\L2PPSSM\'
    executable: '.\bin\SML2PP_start.exe'
    resolution: '25'
    signal: 'L1'
    polarization: 'L'
  L2_FT:
    workingDirectory: 'C:\Users\HydroGNSS\Desktop\L2PPFT\'
    executable: '.\bin\L2PPFT.exe'
  L2_SI:
    workingDirectory: 'C:\Users\HydroGNSS\Desktop\L2PPSI\'
    script: '.\scripts\Run_PSR.py'