start: L1_A # possible values are listed in 'processors' fields (keys)
end: L1_A # possible values are listed in 'processors' fields (keys); ending processor cannot be before the one in 'start' field  (following the order of the list 'processors')
logLevel: DEBUG # for logging purposes
dataRoot: 'C:\Users\HydroGNSS\Desktop\PDGS_NAS_folder' # absolute path to PDGS_NAS_folder
backupRoot: 'C:\Users\HydroGNSS\Desktop\DataRelease_backups' # absolute path to backup folder
backupFile: # relative path to backup file which has to be loaded
dryMode: false
processors: #available processors
  L1_A: 
    workingDirectory: 'C:\Users\HydroGNSS\Desktop\L1APP\' # absolute path to processor delivery folder
    executable: '.\bin\STARTroutine_Simulator_GNSSR.exe' # relative path to processor executable
  L1_B:
    workingDirectory: 'C:\Users\HydroGNSS\Desktop\L1BPP\'
    script: '.\scripts\Run_L1b_Processor_with_dates.py'
  L2_FB: 
    workingDirectory: 'C:\Users\HydroGNSS\Desktop\L2PPFB\'
    executable: '.\bin\L2PP_FB.exe'
  L2_SM:
    workingDirectory: 'C:\Users\HydroGNSS\Desktop\L2PPSSM\'
    executable: '.\bin\SML2PP_start.exe'
    resolution: '25'
    signal: 'L1'
    polarization: 'L'
  L2_FT:
    workingDirectory: 'C:\Users\HydroGNSS\Desktop\L2PPFT\'
    executable: '.\bin\L2PPFT.exe'
  L2_SI:
    workingDirectory: 'C:\Users\HydroGNSS\Desktop\L2PPSI\'
    script: '.\scripts\Run_PSR.py'