PAM: true
backupFile: null
backupRoot: C:\E2ES_backups
dataRoot: C:\PDGS_NAS_Folder
end: L2_SI
logLevel: DEBUG
processors:
  L1_A:
    executable: .\bin\HSAVERS.exe
    workingDirectory: C:\L1A\
  L1_B:
    script: .\Run_L1b_Processor_with_dates.py
    workingDirectory: C:/L1BOP/scripts
  L1_B2:
    script: .\Run_L1Merge_with_dates.py
    workingDirectory: C:/L1OP-MM/scripts
  L2_FB:
    executable: .\L2PP_FB.exe
    workingDirectory: C:\L2FB\bin
  L2_FT:
    executable: .\L2PPFT_mainscript.exe
    workingDirectory: C:\L2FT\bin
  L2_SI:
    executable: .\L1BCC_L2OPSI.exe
    workingDirectory: C:/L2OP-SI/bin
  L2_SM:
    executable: .\bin\SML2OP_start.exe
    workingDirectory: C:\L2SM\
  PAM:
    executable: .\bin\PAM_start.exe
    workingDirectory: C:\PAM\
start: L1_A
